### ISSUE TITLE
Sign-Up Page (frontend)

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#1]
Please develop a sign-up page based on what the designers have designed, you can check the Figma file for the design.

**Comment by Buch-dev** [comment]
Done ma

**Comment by kwindeezah** [comment]
What exactly is done?

**Comment by BlessIknow** [comment]
https://github.com/zuri-training/Team-16_My-CMS/tree/main/frontend/main%20pages/sign-up

**Comment by Buch-dev** [comment]
https://github.com/zuri-training/Team-16_My-CMS/tree/main/frontend/main%20pages/sign-up
