### ISSUE TITLE
Hi-Fi, User research, Template

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#10]
Kindly work on the Hi-Fi, User research, and Template designs.

**Comment by Earl-Taiwo** [comment]
Alright. On it.

Thanks

**Comment by Earl-Taiwo** [comment]
Research Document 

https://docs.google.com/document/d/1GBYpsnggTsAHlmoVQ91C2WfTalp0mnYDaudTR5riDSs/edit?usp=drivesdk

Figjam

<img width="16384" alt="proj＿16_ my＿cms_ Userflow" src="https://user-images.githubusercontent.com/105229281/183254767-35ef13b9-86d0-40a1-b90b-d417664a1a46.png">

https://www.figma.com/file/aIlitF89zEw7aI6JeT65Am/proj%EF%BC%BF16%2F-my%EF%BC%BFcms%2F-Userflow

Figma

![DASHBOARD](https://user-images.githubusercontent.com/105229281/183254801-370014b8-767a-40a9-8cc5-acc04521b154.png)
![FASHION TEMPLATE](https://user-images.githubusercontent.com/105229281/183254803-e6a5adcb-ac24-4c41-8c02-c354361bd5d3.png)
![TEMPLATE PAGE](https://user-images.githubusercontent.com/105229281/183254814-f23234fe-ab88-4bb3-8bfb-d471ce9104e6.png)
![PROMPT PAGE](https://user-images.githubusercontent.com/105229281/183254820-e3174822-5b61-417d-b5f6-6fa091592e0c.png)

https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File
