### ISSUE TITLE
Style guide, Template, User research

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#11]
Kindly work on the Style guide, Template, and User research designs.

**Comment by Design-goddess1** [comment]
I worked on the style guides by generating color styles, input fields and Layout grid system
https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12
![COLOUR](https://user-images.githubusercontent.com/105248925/183285082-ec700140-dba4-463f-b60d-c3ee7d6ac0d7.png)

**Comment by Design-goddess1** [comment]
![INPUT FIELD](https://user-images.githubusercontent.com/105248925/183285122-165a53ab-4f8f-4662-a711-1b4c438fd645.png)

**Comment by Design-goddess1** [comment]
I designed the entertainment template, it allows users to easily navigate and access movies they would want to watch
![ENTERTAINMENT TEMPLATE PAGEHI FI](https://user-images.githubusercontent.com/105248925/183285169-d8e8ef95-1ef2-4f59-84d9-8296e3eaf137.png)

**Comment by Design-goddess1** [comment]
I also worked on the user research file on Fig jam
https://www.figma.com/file/aIlitF89zEw7aI6JeT65Am/proj%EF%BC%BF16%2F-my%EF%BC%BFcms%2F-Userflow

**Comment by Design-goddess1** [comment]
https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12
