### ISSUE TITLE
Hi-Fi, Style guide, Template, User flow

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#13]
Kindly work on the Hi-Fi, Style guide, Template, and User flow designs.

**Comment by Obiinnaa** [comment]
Link to the design file
https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12

I did the designs for some of the style guides, such as buttons, input fields, typography, iconography and components

![Buttons](https://user-images.githubusercontent.com/60512328/183253183-36d47657-8a23-45dc-971f-91900cbd2bc2.png)
![Typography](https://user-images.githubusercontent.com/60512328/183253199-05bc6a78-872a-470d-a327-6a90663b55e8.png)
![INPUT FIELD](https://user-images.githubusercontent.com/60512328/183253211-f3ff9eba-8c1c-4a06-a64f-8946f268c851.png)


I designed the Frequently Asked Questions page on the landing page.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/60512328/183252851-7e38b9f6-35e6-49a8-9e2c-4b867f24c9e9.png">

I did a design of the footer section.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/60512328/183252876-58c822fd-08d4-43e2-b8fe-b7ccd6802d3a.png">


I contributed to the design of the landing page, I made corrections to the alignments of the pages. 
Also, the buttons input fields in the sign-up and sign-in pages were done with @Tsolaye

I was assigned to design one of the templates to be used on the CMS. I designed a personal blog template that allows users to upload blog posts.
![Blog Template](https://user-images.githubusercontent.com/60512328/183253519-93c4f259-f7cb-48c8-938a-d8a17210634c.png)

**Comment by Obiinnaa** [comment]
Link to the design file
https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12

I did the designs for some of the style guides, such as buttons, input fields, typography, iconography and components

![Buttons](https://user-images.githubusercontent.com/60512328/183253183-36d47657-8a23-45dc-971f-91900cbd2bc2.png)
![Typography](https://user-images.githubusercontent.com/60512328/183253199-05bc6a78-872a-470d-a327-6a90663b55e8.png)
![INPUT FIELD](https://user-images.githubusercontent.com/60512328/183253211-f3ff9eba-8c1c-4a06-a64f-8946f268c851.png)

**Comment by Obiinnaa** [comment]
I designed the Frequently Asked Questions page on the landing page.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/60512328/183252851-7e38b9f6-35e6-49a8-9e2c-4b867f24c9e9.png">

I did a design of the footer section.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/60512328/183252876-58c822fd-08d4-43e2-b8fe-b7ccd6802d3a.png">

**Comment by Obiinnaa** [comment]
I contributed to the design of the landing page, I made corrections to the alignments of the pages. 
Also, the buttons input fields in the sign-up and sign-in pages were done with @Tsolaye 

https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12

**Comment by Obiinnaa** [comment]
I was assigned to design one of the templates to be used on the CMS by my team lead. I designed a personal blog template that allows users to upload blog posts.
![Blog Template](https://user-images.githubusercontent.com/60512328/183253519-93c4f259-f7cb-48c8-938a-d8a17210634c.png)

**Comment by Design-goddess1** [comment]
I worked on the style guides by generating color styles, input fields and  Layout grid system
![INPUT FIELD](https://user-images.githubusercontent.com/105248925/183266608-b681a30e-9e45-4768-b152-853a065ce0c8.png)
![COLOUR](https://user-images.githubusercontent.com/105248925/183266656-1cec1360-f9a0-49ce-bba8-3a0a482ee9c0.png)

**Comment by Design-goddess1** [comment]
I designed the entertainment template to be used on the CMS, It allows users to easily navigate and access movies they would want to watch
![ENTERTAINMENT TEMPLATE PAGEHI FI](https://user-images.githubusercontent.com/105248925/183266782-90d501c4-7fd7-4d19-a387-4e70b194a559.png)
