### ISSUE TITLE
Work on project presentation slide 

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#18]
Work on the presentation slide, describing and explaining project details.

**Comment by kwindeezah** [comment]
https://docs.google.com/presentation/d/1msx3Fe5YZP91Yat4kjonbNraTV_rVEj7U1qvJR1r1LA/edit?usp=sharing

**Comment by kwindeezah** [comment]
https://docs.google.com/presentation/d/1msx3Fe5YZP91Yat4kjonbNraTV_rVEj7U1qvJR1r1LA/edit?usp=sharing

**Comment by Kurolinks** [comment]
Seen

**Comment by Earl-Taiwo** [comment]
Noted.
