### ISSUE TITLE
Welcome/Home Page (frontend)

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#2]
Please develop the welcome page based on what the designers have designed, you can check the Figma file for the design.

**Comment by andreu519** [comment]
https://github.com/andreu519/landing-pag
![Screenshot (2)](https://user-images.githubusercontent.com/62018304/182145504-7195c8e7-a5f3-4684-9a07-459fadcd4b6c.png)
![Screenshot (8)](https://user-images.githubusercontent.com/62018304/182145513-24d2f998-9f5f-4028-a899-0b6019136092.png)
e

**Comment by olanrewajurasheed** [comment]
Link to the repository: https://github.com/olanrewajurasheed/my-cms-landingpage


I code and styled our team and testimonies section of the landing page
![mobile (1)](https://user-images.githubusercontent.com/67191099/182161305-95b19ca7-d720-48ef-8a3f-c04fc102b073.gif)

**Comment by andreu519** [comment]
https://andreu519.github.io/WebFlux-landing-page/
![Screenshot (2)](https://user-images.githubusercontent.com/62018304/182203080-5fa30651-5875-478b-8573-e526cfebe577.png)
![Screenshot (8)](https://user-images.githubusercontent.com/62018304/182203086-07e2c253-2512-4344-93c1-7c504ccd41ee.png)


As part of the team building the landing/homepage page, I developed the template section and our users section of the Landing page

**Comment by kwindeezah** [comment]
Good job guys!
