### ISSUE TITLE
Handle Authentication on the Web App

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#20]
Handle user authentication on the web app. Authenticate users so that they can have full access to the website.

**Comment by Kurolinks** [comment]
Noted

**Comment by Ajenipa** [comment]
Ok

**Comment by PreciousDipe** [comment]
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/WebFlux/web_flux_cms/template_app
