### ISSUE TITLE
Develop Blog Template 

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#21]
Please develop the blog template, refer to the Figma file for the design.

https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12

**Comment by andreu519** [comment]
Task done
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/frontend/template%20pages/Blog

**Comment by andreu519** [comment]
Team lead should please verify

**Comment by Buch-dev** [comment]
Done 
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/frontend/template%20pages/Blog
