### ISSUE TITLE
Develop the Fashion Template Page 

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#22]
Develop the fashion template, please refer to the Figma file for the design. 

https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12

**Comment by aishaabdul777** [comment]
I'm done with the fashion template

**Comment by aishaabdul777** [comment]
here is the link to the completed fashion template
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/frontend/template%20pages/Fashion
