### ISSUE TITLE
Develop the Portfolio Template 

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#23]
Develop the Portfolio Template, kindly refer to the Figma file for the design. 

https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12

**Comment by BlessIknow** [comment]
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/frontend/template%20pages/Portfolio%20

**Comment by BlessIknow** [comment]
https://github.com/zuri-training/Team-16_My-CMS/tree/main/frontend/template%20pages/Portfolio%20
