### ISSUE TITLE
develop the Entertainment Template 

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#24]
Develop the entertainment template, refer to the Figma file for the design.

**Comment by AKIN-THOMAS** [comment]
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/frontend/template%20pages/Entertaiment

**Comment by olanrewajurasheed** [comment]
I developed the body of the entertainment template page excluding the hero section and footer

**Comment by AKIN-THOMAS** [comment]
I developed the navigation bar, hero section and the footer
