### ISSUE TITLE
Integrate Pages into the Project Framework using the Django Templating Conventional Method 

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#25]
Integrate pages into the project framework using Django's templating language. Putting into consideration the work of the frontend team, you can also liaise with them to get this done.

**Comment by Ajenipa** [comment]
Ok

**Comment by PreciousDipe** [comment]
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/WebFlux/web_flux_cms/template_app/templates
