### ISSUE TITLE
Create a Database Schema for the Project

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#3]
Create a database schema for the project inclusive of all logical constraints.

**Comment by PreciousDipe** [comment]
https://drive.google.com/file/d/1cCNya3JOhfSnFDM6N6evqCZ6rOYPtuwt/view?usp=drivesdk

**Comment by Bernadettechukwuedo** [comment]
https://drive.google.com/file/d/1cCNya3JOhfSnFDM6N6evqCZ6rOYPtuwt/view?usp=drivesdk

**Comment by yemoche** [comment]
https://drive.google.com/file/d/1cCNya3JOhfSnFDM6N6evqCZ6rOYPtuwt/view?usp=drivesdk

Also suggested the diagram.net / diagram.io used for schema creation.
