### ISSUE TITLE
Template Page (frontend)

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#4]
Please develop a template page based on what the designers have designed, you can check the Figma file for the design.

**Comment by Ajenipa** [comment]
https://github.com/zuri-training/Team-16_My-CMS/tree/main/frontend/main%20pages/template_page

**Comment by Buch-dev** [comment]
Done
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/frontend/main%20pages/template_page
