### ISSUE TITLE
Prompt Page (frontend)

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#6]
Please develop a prompt page based on what the designers have designed, you can check the Figma file for the design.

**Comment by Kurolinks** [comment]
Seen.

**Comment by kwindeezah** [comment]
Great!
Thanks

**Comment by aishaabdul777** [comment]
Okay. Seen

**Comment by aishaabdul777** [comment]
Seen

**Comment by Kurolinks** [comment]
Here is a link to a repository for the Issued task
https://github.com/Kurolinks/Prompt-Page

**Comment by Kurolinks** [comment]
Here is a link to the published webpage on GitHub
https://kurolinks.github.io/Prompt-Page/

**Comment by Kurolinks** [comment]
Find attached a link to the Prompt Page in our Repo
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/frontend/main%20pages/Prompt%20Page

**Comment by aishaabdul777** [comment]
here is the link to the completed prompt page.
https://github.com/zuri-training/Team-16_My-CMS/tree/sub-main/frontend/main%20pages/Prompt%20Page
