### ISSUE TITLE
Hi Fi, Wireframes, User Flow

### ISSUE THREAD

**Issue by kwindeezah** [zuri-training/Team-16_My-CMS#9]
Kindly work on Hi-Fi, Wireframes, and User Flow.

**Comment by Tsolaye** [comment]
Noted ma. Working on it

**Comment by Tsolaye** [comment]
Here is a link to the task
https://www.figma.com/file/uGRymIoFVSIZlZgsuZ65Ks/proj_16%2F-my_cms-Work-File?node-id=23%3A12

During this task, I was able to work with my team to create and also alignments of the following pages

The Landing Page. SignUp. Log in, Forgot Password and logo for the website

I also assisted in aligning all the pages. I also supported by suggesting features that would be available on our Edit page

Below are images of some of the pages, Others can be found in the link above

![Main Landing PageHI FI (1)](https://user-images.githubusercontent.com/85829397/183272576-9e401e9b-5bd7-415b-a1db-4b8aecedce21.jpg)


![SignupHI FI](https://user-images.githubusercontent.com/85829397/183272590-70702bf5-97cd-4e8b-888e-e368d85bce7f.jpg)


![Log inHI FI](https://user-images.githubusercontent.com/85829397/183272599-4a39b7f8-b9e2-4300-be5b-8e134dbde6dc.jpg)


![pop-upHI FI](https://user-images.githubusercontent.com/85829397/183272635-567c4d77-7ffc-49f0-b243-8850c1420245.jpg)


![Frame 488](https://user-images.githubusercontent.com/85829397/183272649-0d4b54d0-4605-4faa-867c-d1f2d0092a84.png)
